# Generated by Django 3.1.6 on 2021-02-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_registrationlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationlocation',
            name='location',
        ),
        migrations.AddField(
            model_name='registrationlocation',
            name='location',
            field=models.ManyToManyField(to='main.Location'),
        ),
    ]
