# Generated by Django 3.1.6 on 2021-02-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210215_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_present',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='описание локации'),
        ),
        migrations.AlterField(
            model_name='registrationlocation',
            name='course_name',
            field=models.CharField(max_length=100, verbose_name='тема мероприятия'),
        ),
        migrations.AlterField(
            model_name='registrationlocation',
            name='course_org',
            field=models.CharField(max_length=100, verbose_name='организатор мероприятия'),
        ),
        migrations.AlterField(
            model_name='registrationlocation',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='почта организатора'),
        ),
        migrations.AlterField(
            model_name='registrationlocation',
            name='inform',
            field=models.TextField(max_length=400, verbose_name='информация'),
        ),
        migrations.AlterField(
            model_name='registrationlocation',
            name='many_course',
            field=models.IntegerField(verbose_name='количество человек'),
        ),
    ]
