# Generated by Django 3.1.6 on 2021-02-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comentary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentary',
            name='location',
        ),
        migrations.AddField(
            model_name='comentary',
            name='location',
            field=models.ManyToManyField(to='main.Location'),
        ),
    ]
